### ISSUE TITLE
'physicalFormat' => 'php:U' support ?

### ISSUE THREAD

**Issue by tecnologiaterabyte** [mdmsoft/yii2-format-converter#2]
Hi mdmunir, excellent converter works properly only if you put unix timestamp adds one day at a date, as I fix greetings.

Thks,

**Comment by mdmunir** [comment]
I am not sure, i have not tes yet :grinning:. But should be work.

**Comment by tecnologiaterabyte** [comment]
I tried it and adds to date one day only has that detail with 'php:U', in the form 'php: d/m/y' works perfectly.

**Comment by tecnologiaterabyte** [comment]
Restart my Vps works perfectly, 'physicalFormat' => 'php:U'  :+1: 

Thks,
