### ISSUE TITLE
No value in DB after "post"

### ISSUE THREAD

**Issue by garsim** [mdmsoft/yii2-format-converter#3]
Hi, 
i'm using this extension to format my date from/to d-m-Y to/from mysql-date but without any result and i don't know why :/

i put this behaviors in my ActiveRecord:

  public function behaviors()
    {
        return [
            [
                'class' => 'mdm\converter\DateConverter',
                'type' => 'date', // 'date', 'time', 'datetime'
                'logicalFormat' => 'php:d-m-Y', // default to locale format
                'physicalFormat' => 'php:Y-m-d', // database level format, default to 'Y-m-d'
                'attributes' => [
                    'data_nascita' => 'datanascita', // datanascita is original attribute
                ]
            ],
        ];
    } 

--------------------------------------
this is my _form 

<?= $form->field($model, 'data_nascita')->widget('yii\jui\DatePicker', [
        'options' => ['class' => 'form-control', 'style' => 'width:50%'],
        'dateFormat' => 'php:d-m-Y',
    ]); ?> 
--------------------------------------
and in my view i use data_nascita instead of datanascita (but the view, now, isn't a problem because in mysql the value of datanascita is null).

Any suggestion?

**Comment by mdmunir** [comment]
add attribute to `rules()`
```php
[
    ...
    [['data_nascita'],'safe'],
]
```

**Comment by garsim** [comment]
good! now it works perfectly! ^^
i've forgotten to modify my old rules from datanascita to data_nascita :-1: 

thank you :)
